# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "limafang"
repo_name: "multimodal-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: False
publish_wechat: False

# file paths
json_readme_path: './docs/multimodal-arxiv-daily.json'

md_readme_path: 'README.md'


keywords:
    "multimodal":
        filters: ["VLM","multimodal fusion","multimodal learning","cross-modal"]
    "computational argumentation":
        filters: ["Computational Argumentation","Argument Mining","Argument Generation","Argument Quality Assessment","LLM Debate"]

