title: Multimodal Arxiv Daily
description: Automatically Update  Multimodal and Computational Argumentation Papers Daily using Github Actions (Update Every 12th hours)
show_downloads: true

github:
  zip_url: https://github.com/KashiwaByte/multimodal-arxiv-daily
  another_url: https://github.com/KashiwaByte/multimodal-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: KashiwaByte

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
